### ISSUE TITLE
Timeout on Issues endpoint

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#1116]
e.g.
https://transit.land/api/v1/issues?category=station_hierarchy&of_feed_entities=f-u09-paris~metro~bus~tram&per_page=0&total=true&embed_issues=true

**Comment by stevevance** [comment]
Here's another example: https://transit.land/api/v1/issues?category=station_hierarchy&of_feed_entities=f-u2f-dpp&per_page=0&total=true&embed_issues=true

**Comment by stevevance** [comment]
This `feed_version_infos` API call on the [Israeli feed](https://transit.land/dispatcher/feeds/f-sv-גלים~מועצהאזוריתגולן~אפיקים~דןצפון~דןבדרום~דןבארשבע~ירושלים) also times out: https://transit.land/api/v1/feed_version_infos?feed_version_sha1=&per_page=false&type=FeedVersionInfoStatistics&total=true&embed_issues=true

It's weird because that API call doesn't have a onestopId parameter.
