### ISSUE TITLE
FeedEater import succeeds, but doesn't persist stops/routes/SSPs because of Exception on ChangePayload validation error

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#687]
Occurring in:
- https://transit.land/dispatcher/feeds/f-c2bt-bctransit~whistlertransitsystem
- https://transit.land/dispatcher/feeds/f-c29-communitytransit

**Comment by drewda** [comment]
Related to: https://github.com/transitland/transitland/issues/62

**Comment by drewda** [comment]
@irees I'm updating this issue, since it looks like the same error just occurred on Community Transit:

https://transit.land/dispatcher/feeds/f-c29-communitytransit

import log:
>Cleanup any existing FeedVersion SSPs
Load GTFS
Load TL
  stops
    Stop: s-c2917kk1d2-marinedrne~27thavene: Marine Dr NE & 27th Ave NE
...
Create changeset
Create: Operators, Stops, Routes
  updating feed bounding box
  operators: 1
  stops: 1506
Error: Validation failed: Payload The property '#/changes/657' of type Hash did not match any of the required schemas in schema file:///srv/www/transitland/releases/20160719162705/app/models/json_schemas/changeset.json#
Payload:
{"id":32536,"payload":{"changes":[{"action":"createUpdate","operator":{"name":"Community Transit","tags":{"agency_id":"29","agency_lang":"en","agency_phone":"(800) 562-1375"},"onestopId":"o-c29-communitytransit","geometry":{"type":"Polygon","coordinates":[[[-122.328871,47.598829],["-122.33176999999998",47.60137700000001],[-122.340239,47.61060500000001],["-122.38471500000001","47.809645999999994"],[-122.369666,48.24236199999999],[-122.367927,48.243658],[-122.34146,48.24674100000001],["-121.99928899999998","48.273464000000004"],["-121.77264599999998","48.278715999999996"],["-121.76451999999999","48.278588000000006"],["-121.75722799999997",48.27799899999999],["-121.66976600000001",48.27076399999999],["-121.63308899999997","48.263182999999984"],["-121.60324099999998",48.25535199999998],[-121.601588,48.25488],["-121.60101300000001","48.251796999999996"],["-121.60096800000001","48.251290000000004"],["-121.69194899999998",47.853091],[-122.194463,47.615493],[-122.328871,47.598829]]]},"timezone":"America/Los_Angeles","shortName":"CT","website":"http://www.communitytransit.org/","country":"United States","state":"Washington","metro":"Seattle","identifiedBy":["gtfs://f-c29-communitytransit/o/29"]}}]},"changeset_id":1969,"created_at":"2016-07-21T23:41:24.623Z","updated_at":"2016-07-21T23:41:24.623Z"}
Changeset apply
  apply done: time 0.047131836
