### ISSUE TITLE
When bulk deactivating issues, make sure it's done asynchronously

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#787]
- in the case of a synchronous changeset application or a feed import, the bulk deactivation can happen in a separate async job
- in the case of an async changeset application, the bulk deactivation can happen as part of the same job

**Comment by doublestranded** [comment]
Now that deprecation of issues depends on one of the associated entities' updated_at times to be greater than the issue updated_at time, it might be best to move all deprecation of issues into Issue.bulk_deactivate, and extend outdated? to include open=false issues instead of having the changeset model deprecate resolving issues.

**Comment by doublestranded** [comment]
#816 indirectly resolves this issue by limiting the selection of issues to deprecate to only those belonging to the entities of the changeset, and the attributes that are changing.
