### ISSUE TITLE
OSM conflation for stops has been failing a lot recently

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#830]
https://sentry.io/mapzen/datastore-prod/issues/160042590/

```
NoMethodError: undefined method `[]' for nil:NilClass
  app/models/stop.rb:287:in `block (3 levels) in conflate_with_osm'
    osm_way_id = tyr_locate_response[index][:edges][0][:way_id]
  app/models/stop.rb:286:in `each'
    group.each_with_index do |stop, index|
  app/models/stop.rb:286:in `each_with_index'
    group.each_with_index do |stop, index|
  app/models/stop.rb:286:in `block (2 levels) in conflate_with_osm'
    group.each_with_index do |stop, index|
  app/models/stop.rb:277:in `block in conflate_with_osm'
    Stop.transaction do
...
(32 additional frame(s) were not displayed)

NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by drewda** [comment]
Lots of Tyr requests to conflate stop locations with OSM way IDs have been failing recently.

//cc @gknisely @kevinkreiser @irees

**Comment by irees** [comment]
I checked as a precaution, and all Stops do have an `osm_way_id`.

```
irb(main):024:0> Stop.count
=> 773709
irb(main):025:0> Stop.where(osm_way_id: nil).count
=> 0
irb(main):026:0> osm_way_ids = Stop.select(:osm_way_id).pluck(:osm_way_id); 0
irb(main):027:0> osm_way_ids.count
=> 773709
irb(main):028:0> osm_way_ids.uniq.count
=> 326475
```

As expected, less than half of `osm_way_id`s are unique, presumably from bus stop pairs.

**Comment by kevinkreiser** [comment]
im not following, is this happening currently? ie you arent getting back valid results from `locate`? if so can you give us a request that fails or a stop that fails so we can look into it?

**Comment by doublestranded** [comment]
Yes @kevinkreiser, this seems to be happening currently (ongoing) according to sentry:
https://sentry.io/mapzen/datastore-prod/issues/160042590/events/4536436056/

I'm not exactly yet sure where the culprit is, or if there are several. There are so many errors (600+) because an exception is raised for each stop of a bad request/response per stop batch. Ian and I are going to grab a specific failed request and try it again.

In the meantime Kibana is telling us that there were 2 "TyrService::Error: Request to Tyr timed out. Is it running?" on October 13th, but none of the other errors :

http://kibana.iad.internal.mapzen.com/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-2M,mode:relative,to:now))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'type:%20*transitland-logs*%20AND%20message:%20%22TyrService::Error:%20Request%20to%20Tyr%20timed%20out.%20Is%20it%20running%3F%22')),sort:!('@timestamp',desc))

**Comment by kevinkreiser** [comment]
i dont have access to sentry but if you can find a failing one please pass it along. all i really need is the lat,lon

**Comment by doublestranded** [comment]
Oops, sorry about that. We're looking for a lat/lng that fails.

**Comment by doublestranded** [comment]
@kevinkreiser we found the culprit (or one at least) - a "null island" lat/lng (0.0,0.0) stop location, and we aren't guarding for that. Thanks for your help!

**Comment by kevinkreiser** [comment]
was going to say it but didnt dare to be so bold :wink:

**Comment by gknisely** [comment]
Could this be the issue with the Paris feeds?

**Comment by irees** [comment]
@greg I thought so, but I checked and all Paris stops have osm_way_id's.

**Comment by gknisely** [comment]
k thanks
